[general]
allowed_file_endings = [".mkv", ".avi", ".mp4"]
listen_network = "tcp"
listen_addr = ":8888"
path_prefix = "/scrubarr"

[general.auth]
username = "blinks"
password_salt = ""
password_hash = ""

[general.auth.jwt]
private_key_path = ""
public_key_path = ""

[connections]

[connections.sonarr]
enabled = true
hostname = "https://somedomain.com/sonarr/"
api_key = ""


[connections.radarr]
enabled = true
hostname = "https://somedomain.com/radarr/"
api_key = ""

[connections.deluge]
enabled = true
hostname = "some.host.na.me"
port = 16156
username = "admin"
password = ""

[connections.rtorrent]
enabled = true
hostname = "https://somedomain.com/rtorrent/RPC2/"
username = "admin"
password = ""
